apiVersion: v1
kind: Namespace
metadata:
  name: it-tools
  labels:
    name: it-tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app: it-tools
    app.kubernetes.io/name: it-tools
    app.kubernetes.io/instance: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
        app.kubernetes.io/name: it-tools
        app.kubernetes.io/instance: it-tools
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: nginx-tmp
        emptyDir: {}
      containers:
      - name: it-tools
        image: corentinth/it-tools:latest  # Use specific tag instead of latest
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: nginx-tmp
          mountPath: /tmp
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app: it-tools
    app.kubernetes.io/name: it-tools
spec:
  selector:
    app: it-tools
  ports:
  - port: 80
    targetPort: http
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app: it-tools
    app.kubernetes.io/name: it-tools
  annotations:
    cert-manager.io/cluster-issuer: self-signed
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    # External DNS annotation if using external-dns operator
    # external-dns.alpha.kubernetes.io/hostname: it-tools.eduuh.home
    external-dns.alpha.kubernetes.io/target: "10.0.0.24"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - it-tools.eduuh.home
    secretName: it-tools-tls
  rules:
  - host: it-tools.eduuh.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: it-tools
            port:
              name: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: it-tools
  namespace: it-tools
  labels:
    app: it-tools
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: it-tools
