apiVersion: v1
kind: Namespace
metadata:
  name: glance
  labels:
    name: glance
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    theme:
      light: false
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: clock
                hour-format: 24h
              - type: weather
                location: Nairobi, Kenya
          - size: full
            widgets:
              - type: videos
                title: YouTube
                style: horizontal-cards
                limit: 4
                channels:
                  - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                  - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
              - type: rss
                title: Blogs
                style: horizontal-cards
                limit: 4
                feeds:
                  - url: https://kubernetes.io/feed.xml
                    title: Kubernetes Blog
                  - url: https://www.jeffgeerling.com/blog.xml
                    title: Jeff Geerling
          - size: small
            widgets:
              - type: monitor
                title: Status
                sites:
                  - title: IT Tools
                    url: https://tools.eduuh.home
                  - title: Nextcloud
                    url: https://nextcloud.eduuh.home
                  - title: Immich
                    url: https://photos.eduuh.home
                    icon: mdi:tools
                    allow-insecure: true
                  - title: Glance
                    url: https://glance.eduuh.home
                    icon: si:glance
                    allow-insecure: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
  labels:
    app: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      containers:
        - name: glance
          image: glanceapp/glance:v0.8.4
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config/glance.yml
              subPath: glance.yml
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: glance-config
---
apiVersion: v1
kind: Service
metadata:
  name: glance
  namespace: glance
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: glance
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance
  namespace: glance
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - glance.eduuh.home
      secretName: glance-tls
  rules:
    - host: glance.eduuh.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glance
                port:
                  number: 80
