apiVersion: v1
kind: Secret
metadata:
    name: podinfo-secret
    namespace: podinfo
stringData:
    username: ENC[AES256_GCM,data:MqebArQ=,iv:vlJ51TW+jDcKTpH8PAmkjA2lWwuvH0hsWSUnW4aXprM=,tag:l9f47aDTBdUVOCGmPoaYrQ==,type:str]
    password: ENC[AES256_GCM,data:/lu1QFDdeuVt24HVMlCFF28NaA==,iv:A62oa9lxbNQtmJcVCIsnJJEfj7zLJHoPvjYtxEsV7RY=,tag:ENRY+fgwdBTZgcyvGJGynw==,type:str]
sops:
    age:
        - recipient: age123qz4jtnncp3l87a722303xxvs7jf33melrt3m63kqp0r34304zsdfhlm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZldPMzhrVXZPeWZwTlgy
            MEtxMG9sMklxV01lc2lVcitYZUIyOTM1NVQwCjBVdWQ2TVYvU0RBQm85NFVWUG83
            N0RhR3BnSGxsVktQd0k2cUxXaTRwMDgKLS0tIDdQRSs3NEprSDYzbkdDZkhRVzFM
            dzFTWWRYY2xKYnBsUWJRc051RC9wY28KuZghJ+tHP6wbgSguB+E1ygzrLEKfh95l
            n8paXlyw7bH1UUSNx4I6Ao4HNoGfyb2UeOHH586Q3JrsWAzSHROC/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T14:33:36Z"
    mac: ENC[AES256_GCM,data:UO7pWedwnydZcCtc3wtMXxljFpoYmGxpDWk9xoU2sZPdc4eErQhSoVD7sxLUfbzsNWdRb1fEr0afkAkIIBOo5YLefF4D2UzxDPLvECTLRzptqDDWUp2cYLshm8mKV4gggF1tjLzxCnC0KB7C2vT/aF44uSkut1CoSep8PR9i85w=,iv:WVtu8LXsv1PoTjpqq1malZrU9pBp096Exvos+FSeinY=,tag:kZd/dQYJ6K2iHEr+sIBjLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
